import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from 'next/image';
import sampleUviversityIcon from "../public/sampleUniversity.png";
import "./globals.css";
import css from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          {/* 大学のロゴ（実際の画像ファイルに差し替え） */}
          <Image src={sampleUviversityIcon} alt="ABC大学ロゴ" className={css.logo} />
          <h1>ABC大学 学生専用過去問サイト</h1>
          <p>あなたの学びをサポートする試験対策コミュニティ</p>
        </header>

        {children}
        
        <footer>
          <p>&copy; 2025 ABC大学 学生専用過去問サイト</p>
        </footer>
      </body>
    </html>
  );
}
