import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import sampleUviversityIcon from "@/public/sampleUniversity.png";
import Header from "../components/header";
import Footer from "../components/footer";
import "./globals.css";
import { StaticImageData } from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface head {
  year: number
  university: string
  site: string
  phrase: string
  uniImage: StaticImageData
}

const head: head = {
  year: 2025,
  university: "ABC大学",
  site: "学生専用過去問サイト",
  phrase: "あなたの学びをサポートする試験対策コミュニティ",
  uniImage: sampleUviversityIcon,
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${ geistSans.variable } ${ geistMono.variable }`}>
        <Header head={ head }></Header>

        { children }
        
        <Footer head={ head }></Footer>
      </body>
    </html>
  );
}
