services:
  app:
    build: ./go
    container_name: mathsys_backend
    ports:
      - "8000:8000"
    volumes:
      - ./go:/app
    environment:
      TZ: Asia/Tokyo
    tty: true # コンテナが稼働し続ける設定

  mysql:
    image: mysql:8.0
    container_name: mathsys_database
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - mathsys_db:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mathsys_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo

volumes:
  mathsys_db: