services:
  frontend:
    build: ./frontend
    container_name: mathsys_fronntend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      # - ./frontend/node_modules:/usr/src/app/node_modules
    command: sh -c "npm run dev"
  backend:
    build: ./go
    container_name: mathsys_backend
    ports:
      - "8000:8000"
    volumes:
      - ./go:/app
    environment:
      TZ: Asia/Tokyo
    tty: true # コンテナが稼働し続ける設定
  mysql:
    image: mysql:8.0
    container_name: mathsys_database
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - mathsys_db:/var/lib/mysql
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: mathsys_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo

volumes:
  mathsys_db:
  # node_modules: